<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>src/git_info.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&quot;git_info.h&quot;<br>
<br>
#include&nbsp;&lt;cstdio&gt;<br>
#include&nbsp;&lt;string&gt;<br>
<br>
//&nbsp;Runs&nbsp;a&nbsp;shell&nbsp;command&nbsp;and&nbsp;captures&nbsp;its&nbsp;stdout.<br>
//&nbsp;Returns&nbsp;empty&nbsp;string&nbsp;on&nbsp;error&nbsp;or&nbsp;if&nbsp;nothing&nbsp;was&nbsp;printed.<br>
static&nbsp;std::string&nbsp;run_command_capture(const&nbsp;char&nbsp;*cmd)<br>
{<br>
#ifdef&nbsp;_WIN32<br>
&nbsp;&nbsp;&nbsp;&nbsp;FILE&nbsp;*pipe&nbsp;=&nbsp;_popen(cmd,&nbsp;&quot;r&quot;);<br>
#else<br>
&nbsp;&nbsp;&nbsp;&nbsp;FILE&nbsp;*pipe&nbsp;=&nbsp;popen(cmd,&nbsp;&quot;r&quot;);<br>
#endif<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!pipe)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;{};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;result;<br>
&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;buffer[256];<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(fgets(buffer,&nbsp;sizeof(buffer),&nbsp;pipe))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;+=&nbsp;buffer;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
#ifdef&nbsp;_WIN32<br>
&nbsp;&nbsp;&nbsp;&nbsp;_pclose(pipe);<br>
#else<br>
&nbsp;&nbsp;&nbsp;&nbsp;pclose(pipe);<br>
#endif<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;strip&nbsp;trailing&nbsp;newlines<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(!result.empty()&nbsp;&amp;&amp;&nbsp;(result.back()&nbsp;==&nbsp;'\n'&nbsp;||&nbsp;result.back()&nbsp;==&nbsp;'\r'))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result.pop_back();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;result;<br>
}<br>
<br>
GitInfo&nbsp;detect_git_info()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;GitInfo&nbsp;info;<br>
<br>
#ifdef&nbsp;_WIN32<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;commit&nbsp;=&nbsp;run_command_capture(&quot;git&nbsp;rev-parse&nbsp;HEAD&nbsp;2&gt;nul&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;remote&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;run_command_capture(&quot;git&nbsp;config&nbsp;--get&nbsp;remote.origin.url&nbsp;2&gt;nul&quot;);<br>
#else<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;commit&nbsp;=&nbsp;run_command_capture(&quot;git&nbsp;rev-parse&nbsp;HEAD&nbsp;2&gt;/dev/null&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;remote&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;run_command_capture(&quot;git&nbsp;config&nbsp;--get&nbsp;remote.origin.url&nbsp;2&gt;/dev/null&quot;);<br>
#endif<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!commit.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;info.commit&nbsp;=&nbsp;commit;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;info.has_commit&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!remote.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;info.remote&nbsp;=&nbsp;remote;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;info.has_remote&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;info;<br>
}<br>
<br>
//&nbsp;Разбор&nbsp;remote&nbsp;вроде&nbsp;git@github.com:user/repo.git&nbsp;или<br>
//&nbsp;https://github.com/user/repo(.git)<br>
bool&nbsp;parse_github_remote(const&nbsp;std::string&nbsp;&amp;remote,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;&amp;user,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;&amp;repo)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::string&nbsp;host&nbsp;=&nbsp;&quot;github.com&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;pos&nbsp;=&nbsp;remote.find(host);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pos&nbsp;==&nbsp;std::string::npos)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;false;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;pos&nbsp;+=&nbsp;host.size();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;пропускаем&nbsp;':'&nbsp;или&nbsp;'/'&nbsp;после&nbsp;github.com<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(pos&nbsp;&lt;&nbsp;remote.size()&nbsp;&amp;&amp;&nbsp;(remote[pos]&nbsp;==&nbsp;':'&nbsp;||&nbsp;remote[pos]&nbsp;==&nbsp;'/'))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;++pos;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pos&nbsp;&gt;=&nbsp;remote.size())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;false;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;user&nbsp;/&nbsp;repo[.git]&nbsp;/&nbsp;...<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;slash1&nbsp;=&nbsp;remote.find('/',&nbsp;pos);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(slash1&nbsp;==&nbsp;std::string::npos)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;false;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;user&nbsp;=&nbsp;remote.substr(pos,&nbsp;slash1&nbsp;-&nbsp;pos);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;start_repo&nbsp;=&nbsp;slash1&nbsp;+&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(start_repo&nbsp;&gt;=&nbsp;remote.size())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;false;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;slash2&nbsp;=&nbsp;remote.find('/',&nbsp;start_repo);<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;repo_part&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(slash2&nbsp;==&nbsp;std::string::npos)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;?&nbsp;remote.substr(start_repo)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;remote.substr(start_repo,&nbsp;slash2&nbsp;-&nbsp;start_repo);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;обрежем&nbsp;.git&nbsp;в&nbsp;конце,&nbsp;если&nbsp;есть<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::string&nbsp;dot_git&nbsp;=&nbsp;&quot;.git&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(repo_part.size()&nbsp;&gt;&nbsp;dot_git.size()&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;repo_part.compare(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;repo_part.size()&nbsp;-&nbsp;dot_git.size(),&nbsp;dot_git.size(),&nbsp;dot_git)&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;repo_part.resize(repo_part.size()&nbsp;-&nbsp;dot_git.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(user.empty()&nbsp;||&nbsp;repo_part.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;false;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;repo&nbsp;=&nbsp;repo_part;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;true;<br>
}<br>
<br>
GitHubInfo&nbsp;detect_github_info()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;GitInfo&nbsp;gi&nbsp;=&nbsp;detect_git_info();<br>
&nbsp;&nbsp;&nbsp;&nbsp;GitHubInfo&nbsp;out;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!gi.has_commit&nbsp;||&nbsp;!gi.has_remote)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;out;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!parse_github_remote(gi.remote,&nbsp;out.user,&nbsp;out.repo))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;out;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;out.commit&nbsp;=&nbsp;gi.commit;<br>
&nbsp;&nbsp;&nbsp;&nbsp;out.ok&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;out;<br>
}<br>
<br>
std::string&nbsp;detect_git_dir()<br>
{<br>
#ifdef&nbsp;_WIN32<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;run_command_capture(&quot;git&nbsp;rev-parse&nbsp;--git-dir&nbsp;2&gt;nul&quot;);<br>
#else<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;run_command_capture(&quot;git&nbsp;rev-parse&nbsp;--git-dir&nbsp;2&gt;/dev/null&quot;);<br>
#endif<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
