<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>src/symbols.h</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#pragma&nbsp;once<br>
<br>
#include&nbsp;&lt;cstddef&gt;<br>
#include&nbsp;&lt;string&gt;<br>
#include&nbsp;&lt;vector&gt;<br>
<br>
//&nbsp;Диапазон&nbsp;строк&nbsp;в&nbsp;файле&nbsp;(0-based,&nbsp;включительно).<br>
struct&nbsp;Region<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;start_line&nbsp;=&nbsp;-1;&nbsp;//&nbsp;inclusive<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;end_line&nbsp;=&nbsp;-1;&nbsp;&nbsp;&nbsp;//&nbsp;inclusive<br>
};<br>
<br>
//&nbsp;Простейший&nbsp;поисковик&nbsp;C++-символов.<br>
//&nbsp;Умеет:<br>
//&nbsp;&nbsp;&nbsp;*&nbsp;находить&nbsp;определение&nbsp;класса&nbsp;(class&nbsp;/&nbsp;struct)<br>
//&nbsp;&nbsp;&nbsp;*&nbsp;искать&nbsp;методы&nbsp;внутри&nbsp;класса&nbsp;(по&nbsp;имени)<br>
class&nbsp;CppSymbolFinder<br>
{<br>
public:<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;text&nbsp;—&nbsp;полный&nbsp;текст&nbsp;файла.<br>
&nbsp;&nbsp;&nbsp;&nbsp;explicit&nbsp;CppSymbolFinder(const&nbsp;std::string&nbsp;&amp;text);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::vector&lt;std::string&gt;&nbsp;&amp;lines()&nbsp;const<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_lines;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Находит&nbsp;определение&nbsp;класса&nbsp;(НЕ&nbsp;forward-declaration).<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Возвращает&nbsp;true,&nbsp;если&nbsp;класс&nbsp;найден.<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;find_class(const&nbsp;std::string&nbsp;&amp;class_name,&nbsp;Region&nbsp;&amp;out)&nbsp;const;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Находит&nbsp;метод&nbsp;внутри&nbsp;класса&nbsp;(по&nbsp;имени).<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Ищет&nbsp;только&nbsp;внутри&nbsp;тела&nbsp;class/struct&nbsp;class_name.<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Возвращает&nbsp;диапазон&nbsp;строк&nbsp;от&nbsp;начала&nbsp;объявления/определения<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;до&nbsp;';'&nbsp;или&nbsp;закрывающей&nbsp;'}'.<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;find_method(const&nbsp;std::string&nbsp;&amp;class_name,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::string&nbsp;&amp;method_name,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Region&nbsp;&amp;out)&nbsp;const;<br>
<br>
private:<br>
&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;Token<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;enum&nbsp;Kind<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Identifier,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Keyword,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Symbol<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;kind;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;text;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;line&nbsp;=&nbsp;0;&nbsp;//&nbsp;0-based<br>
&nbsp;&nbsp;&nbsp;&nbsp;};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;ClassRange<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Region&nbsp;region;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::size_t&nbsp;body_start_token&nbsp;=&nbsp;0;&nbsp;//&nbsp;индекс&nbsp;'{'<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::size_t&nbsp;body_end_token&nbsp;=&nbsp;0;&nbsp;&nbsp;&nbsp;//&nbsp;индекс&nbsp;'}'&nbsp;(или&nbsp;'};')<br>
&nbsp;&nbsp;&nbsp;&nbsp;};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::string&gt;&nbsp;m_lines;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;Token&gt;&nbsp;m_tokens;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;tokenize(const&nbsp;std::string&nbsp;&amp;text);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;bool&nbsp;is_ident_start(char&nbsp;c);<br>
&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;bool&nbsp;is_ident_char(char&nbsp;c);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;find_class_internal(const&nbsp;std::string&nbsp;&amp;class_name,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ClassRange&nbsp;&amp;out)&nbsp;const;<br>
};<br>
<br>
//&nbsp;Простейший&nbsp;поисковик&nbsp;Python-символов.<br>
//&nbsp;Умеет:<br>
//&nbsp;&nbsp;&nbsp;*&nbsp;находить&nbsp;определение&nbsp;класса&nbsp;(class&nbsp;Foo:)<br>
//&nbsp;&nbsp;&nbsp;*&nbsp;искать&nbsp;методы&nbsp;внутри&nbsp;класса&nbsp;(def&nbsp;bar(self,&nbsp;...))<br>
class&nbsp;PythonSymbolFinder<br>
{<br>
public:<br>
&nbsp;&nbsp;&nbsp;&nbsp;explicit&nbsp;PythonSymbolFinder(const&nbsp;std::string&nbsp;&amp;text);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::vector&lt;std::string&gt;&nbsp;&amp;lines()&nbsp;const<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_lines;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Находит&nbsp;определение&nbsp;класса&nbsp;(первое&nbsp;вхождение&nbsp;с&nbsp;таким&nbsp;именем).<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Region&nbsp;покрывает&nbsp;строку&nbsp;'class&nbsp;...'&nbsp;и&nbsp;всё&nbsp;тело&nbsp;класса&nbsp;до&nbsp;dedent.<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;find_class(const&nbsp;std::string&nbsp;&amp;class_name,&nbsp;Region&nbsp;&amp;out)&nbsp;const;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Находит&nbsp;метод&nbsp;внутри&nbsp;класса.<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Ищет&nbsp;def&nbsp;/&nbsp;async&nbsp;def&nbsp;с&nbsp;именем&nbsp;method_name,<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;являющийся&nbsp;&quot;первым&nbsp;уровнем&quot;&nbsp;внутри&nbsp;тела&nbsp;class_name.<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Region&nbsp;покрывает&nbsp;строку&nbsp;def&nbsp;(включая&nbsp;декораторы&nbsp;над&nbsp;ней)&nbsp;и&nbsp;всё&nbsp;тело&nbsp;до<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;dedent.<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;find_method(const&nbsp;std::string&nbsp;&amp;class_name,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::string&nbsp;&amp;method_name,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Region&nbsp;&amp;out)&nbsp;const;<br>
<br>
private:<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::string&gt;&nbsp;m_lines;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;int&nbsp;calc_indent(const&nbsp;std::string&nbsp;&amp;line);<br>
&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;std::size_t&nbsp;first_code_pos(const&nbsp;std::string&nbsp;&amp;line);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;find_class_internal(const&nbsp;std::string&nbsp;&amp;class_name,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Region&nbsp;&amp;out,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;&amp;class_indent)&nbsp;const;<br>
};<br>
<!-- END SCAT CODE -->
</body>
</html>
