#include "chunk_help.h"
#include <iostream>

void print_chunk_help()
{
    std::cout
        << "# Chunk v2 — Change Description Format\n"
           "\n"
           "Chunk v2 is a plain-text format for describing modifications to "
           "source files.\n"
           "A patch consists of multiple sections, each describing a single "
           "operation:\n"
           "line-based edits, text-based edits, or file-level operations.\n"
           "\n"
           "---\n"
           "\n"
           "## 1. Section structure\n"
           "\n"
           "=== file: <path> ===\n"
           "<command>\n"
           "<content...>\n"
           "=END=\n"
           "\n"
           "* <path> — relative file path\n"
           "* Empty lines between sections are allowed\n"
           "* Exactly one command per section\n"
           "* <content> may contain any lines, including empty ones\n"
           "\n"
           "---\n"
           "\n"
           "## 3. Commands (text-based)\n"
           "\n"
           "Two formats are supported for text-based commands:\n"
           "\n"
           "### 3.1 Legacy format (simple)\n"
           "These commands match an exact multi-line marker in the file.\n"
           "Everything before the first `---` is the marker; everything after "
           "it is content.\n"
           "\n"
           "### Insert after marker\n"
           "--- insert-after-text\n"
           "<marker lines...>\n"
           "---\n"
           "<inserted lines...>\n"
           "=END=\n"
           "\n"
           "### Insert before marker\n"
           "--- insert-before-text\n"
           "<marker lines...>\n"
           "---\n"
           "<inserted lines...>\n"
           "=END=\n"
           "\n"
           "### Replace marker\n"
           "--- replace-text\n"
           "<marker lines...>\n"
           "---\n"
           "<new lines...>\n"
           "=END=\n"
           "\n"
           "### Delete marker\n"
           "--- delete-text\n"
           "<marker lines...>\n"
           "---\n"
           "=END=\n"
           "\n"
           "---\n"
           "\n"
           "### 3.2 YAML strict format\n"
           "\n"
           "In YAML mode you can also specify strict context around the "
           "marker:\n"
           "\n"
           "--- replace-text\n"
           "BEFORE:\n"
           "  <lines that must appear immediately above the marker>\n"
           "MARKER:\n"
           "  <marker lines>\n"
           "AFTER:\n"
           "  <lines that must appear immediately below the marker>\n"
           "---\n"
           "<payload lines...>\n"
           "=END=\n"
           "\n"
           "Rules:\n"
           "* YAML mode is enabled only when the first non-empty line after "
           "the command\n"
           "  is one of: `BEFORE:`, `MARKER:`, `AFTER:`.\n"
           "* Matching is strict: BEFORE lines must be directly above the "
           "marker block;\n"
           "  AFTER lines must be directly below it.\n"
           "* Whitespace differences are ignored (lines are trimmed before "
           "comparison).\n"
           "* If BEFORE/AFTER are present, there is no fallback to the first "
           "occurrence\n"
           "  of the marker.\n"
           "* If more than one place matches the strict context, the patch "
           "fails as\n"
           "  ambiguous.\n"
           "* If no place matches the strict context, the patch fails with\n"
           "  \"strict marker context not found\".\n"
           "\n"
           "---\n"
           "\n"
           "## 4. File-level commands\n"
           "These operations work on the whole file rather than its contents.\n"
           "\n"
           "### Create or overwrite file\n"
           "--- create-file\n"
           "<file content...>\n"
           "=END=\n"
           "\n"
           "### Delete file\n"
           "--- delete-file\n"
           "=END=\n"
           "\n"
           "---\n"
           "\n"
           "## 5. Examples\n"
           "\n"
           "=== file: src/a.cpp ===\n"
           "--- replace 3:4\n"
           "int value = 42;\n"
           "std::cout << value << \"\\\\n\";\n"
           "=END=\n"
           "\n"
           "=== file: src/b.cpp ===\n"
           "--- insert-after 12\n"
           "log_debug(\"checkpoint reached\");\n"
           "=END=\n"
           "\n"
           "=== file: src/c.cpp ===\n"
           "--- delete 20:25\n"
           "=END=\n"
           "\n"
           "=== file: assets/config.json ===\n"
           "--- create-file\n"
           "{ \"version\": 1 }\n"
           "=END=\n"
           "\n"
           "=== file: old/temp.txt ===\n"
           "--- delete-file\n"
           "=END=\n"
           "\n"
           "---\n"
           "\n"
           "## Recommended usage\n"
           "* Prefer text-based commands (`*-text`) — they are more stable "
           "when code moves.\n"
           "* Use file-level commands when creating or removing entire files.\n"
           "* Group modifications to multiple files into **one patch file**.\n"
           "\n"
           "*This cheat sheet is in the text for a reason. If you're asked to "
           "write a patch,\n"
           " use the following format: chunk_v2.\n"
           "*Try to strictly follow the rules described in this document, "
           "without making any\n"
           " syntactic errors.\n"
           "*When working with chunks, be careful that commands do not "
           "reference the same\n"
           " text macros. Macros should never overlap.\n";
}