<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>tests/main.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#define&nbsp;DOCTEST_CONFIG_IMPLEMENT<br>
#include&nbsp;&quot;doctest/doctest.h&quot;<br>
#include&nbsp;&lt;string&gt;<br>
#include&nbsp;&lt;vector&gt;<br>
#if&nbsp;defined(__WIN32__)&nbsp;||&nbsp;defined(_MSC_VER)<br>
#include&nbsp;&lt;winsock2.h&gt;<br>
WSADATA&nbsp;wsaData;<br>
#endif<br>
<br>
int&nbsp;main(int&nbsp;argc,&nbsp;char&nbsp;**argv)<br>
{<br>
#if&nbsp;defined(__WIN32__)&nbsp;||&nbsp;defined(_MSC_VER)<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;iResult;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Initialize&nbsp;Winsock<br>
&nbsp;&nbsp;&nbsp;&nbsp;iResult&nbsp;=&nbsp;WSAStartup(MAKEWORD(2,&nbsp;2),&nbsp;&amp;wsaData);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(iResult&nbsp;!=&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf(&quot;WSAStartup&nbsp;failed:&nbsp;%d\n&quot;,&nbsp;iResult);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
#endif<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::string&gt;&nbsp;adjusted_args;<br>
&nbsp;&nbsp;&nbsp;&nbsp;adjusted_args.reserve(argc);<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(int&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;argc;&nbsp;++i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;current(argv[i]);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;((current&nbsp;==&nbsp;&quot;--test-case&quot;&nbsp;||&nbsp;current&nbsp;==&nbsp;&quot;-tc&quot;)&nbsp;&amp;&amp;&nbsp;i&nbsp;+&nbsp;1&nbsp;&lt;&nbsp;argc)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;pattern(argv[i&nbsp;+&nbsp;1]);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pattern.find('*')&nbsp;==&nbsp;std::string::npos)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pattern&nbsp;=&nbsp;&quot;*&quot;&nbsp;+&nbsp;pattern&nbsp;+&nbsp;&quot;*&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;adjusted_args.push_back(current&nbsp;+&nbsp;&quot;=&quot;&nbsp;+&nbsp;pattern);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;++i;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;adjusted_args.push_back(std::move(current));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;char&nbsp;*&gt;&nbsp;argv_adjusted;<br>
&nbsp;&nbsp;&nbsp;&nbsp;argv_adjusted.reserve(adjusted_args.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;arg&nbsp;:&nbsp;adjusted_args)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;argv_adjusted.push_back(arg.data());<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;doctest::Context&nbsp;context;<br>
&nbsp;&nbsp;&nbsp;&nbsp;context.applyCommandLine(static_cast&lt;int&gt;(argv_adjusted.size()),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;argv_adjusted.data());<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;res&nbsp;=&nbsp;context.run();&nbsp;&nbsp;//&nbsp;run<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(context.shouldExit())&nbsp;//&nbsp;important&nbsp;-&nbsp;query&nbsp;flags&nbsp;(and&nbsp;--exit)&nbsp;rely&nbsp;on<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;the&nbsp;user&nbsp;doing&nbsp;this<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;res;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;propagate&nbsp;the&nbsp;result&nbsp;of&nbsp;the&nbsp;tests<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;client_stuff_return_code&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;res&nbsp;+&nbsp;client_stuff_return_code;&nbsp;//&nbsp;the&nbsp;result&nbsp;from&nbsp;doctest&nbsp;is<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;propagated&nbsp;here&nbsp;as&nbsp;well<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
