<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>tests/paths_glob.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&quot;collector.h&quot;<br>
#include&nbsp;&quot;doctest/doctest.h&quot;<br>
#include&nbsp;&quot;options.h&quot;<br>
<br>
#include&nbsp;&lt;algorithm&gt;<br>
#include&nbsp;&lt;filesystem&gt;<br>
#include&nbsp;&lt;fstream&gt;<br>
#include&nbsp;&lt;vector&gt;<br>
<br>
namespace&nbsp;fs&nbsp;=&nbsp;std::filesystem;<br>
<br>
static&nbsp;void&nbsp;write_file(const&nbsp;fs::path&nbsp;&amp;p,&nbsp;const&nbsp;std::string&nbsp;&amp;text)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;fs::create_directories(p.parent_path());<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::ofstream&nbsp;out(p);<br>
&nbsp;&nbsp;&nbsp;&nbsp;out&nbsp;&lt;&lt;&nbsp;text;<br>
}<br>
<br>
static&nbsp;std::vector&lt;std::string&gt;&nbsp;to_rel(const&nbsp;std::vector&lt;fs::path&gt;&nbsp;&amp;v,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;fs::path&nbsp;&amp;root)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::string&gt;&nbsp;out;<br>
&nbsp;&nbsp;&nbsp;&nbsp;out.reserve(v.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;p&nbsp;:&nbsp;v)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;out.push_back(fs::relative(p,&nbsp;root).generic_string());<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::sort(out.begin(),&nbsp;out.end());<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;out;<br>
}<br>
<br>
static&nbsp;void&nbsp;check_paths(const&nbsp;std::vector&lt;std::string&gt;&nbsp;&amp;actual,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::initializer_list&lt;const&nbsp;char&nbsp;*&gt;&nbsp;expected)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::string&gt;&nbsp;exp_vec;<br>
&nbsp;&nbsp;&nbsp;&nbsp;exp_vec.reserve(expected.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;*e&nbsp;:&nbsp;expected)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;exp_vec.emplace_back(e);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::string&gt;&nbsp;act&nbsp;=&nbsp;actual;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::sort(exp_vec.begin(),&nbsp;exp_vec.end());<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::sort(act.begin(),&nbsp;act.end());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(act.size()&nbsp;==&nbsp;exp_vec.size());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(act.size()&nbsp;!=&nbsp;exp_vec.size())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;&nbsp;//&nbsp;предотвратить&nbsp;каскад&nbsp;ошибок<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(size_t&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;act.size();&nbsp;++i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK(act[i]&nbsp;==&nbsp;exp_vec[i]);<br>
}<br>
<br>
TEST_CASE(&quot;collect_from_paths:&nbsp;basic&nbsp;*&nbsp;glob&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;fs::path&nbsp;tmp&nbsp;=&nbsp;fs::temp_directory_path()&nbsp;/&nbsp;&quot;paths_glob_test_1&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;fs::remove_all(tmp);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;write_file(tmp&nbsp;/&nbsp;&quot;a.txt&quot;,&nbsp;&quot;A&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;write_file(tmp&nbsp;/&nbsp;&quot;b.cpp&quot;,&nbsp;&quot;B&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;write_file(tmp&nbsp;/&nbsp;&quot;c.txt&quot;,&nbsp;&quot;C&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Options&nbsp;opt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::string&gt;&nbsp;paths&nbsp;=&nbsp;{(tmp&nbsp;/&nbsp;&quot;*.txt&quot;).generic_string()};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;out&nbsp;=&nbsp;collect_from_paths(paths,&nbsp;opt);<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;rel&nbsp;=&nbsp;to_rel(out,&nbsp;tmp);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;check_paths(rel,&nbsp;{&quot;a.txt&quot;,&nbsp;&quot;c.txt&quot;});<br>
}<br>
<br>
TEST_CASE(&quot;collect_from_paths:&nbsp;recursive&nbsp;**&nbsp;glob&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;fs::path&nbsp;tmp&nbsp;=&nbsp;fs::temp_directory_path()&nbsp;/&nbsp;&quot;paths_glob_test_2&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;fs::remove_all(tmp);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;write_file(tmp&nbsp;/&nbsp;&quot;1.txt&quot;,&nbsp;&quot;A&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;write_file(tmp&nbsp;/&nbsp;&quot;x/2.txt&quot;,&nbsp;&quot;B&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;write_file(tmp&nbsp;/&nbsp;&quot;x/y/3.txt&quot;,&nbsp;&quot;C&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Options&nbsp;opt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::string&gt;&nbsp;paths&nbsp;=&nbsp;{(tmp&nbsp;/&nbsp;&quot;**/*.txt&quot;).generic_string()};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;out&nbsp;=&nbsp;collect_from_paths(paths,&nbsp;opt);<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;rel&nbsp;=&nbsp;to_rel(out,&nbsp;tmp);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;check_paths(rel,&nbsp;{&quot;1.txt&quot;,&nbsp;&quot;x/2.txt&quot;,&nbsp;&quot;x/y/3.txt&quot;});<br>
}<br>
<br>
TEST_CASE(&quot;collect_from_paths_with_excludes:&nbsp;basic&nbsp;exclude&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;fs::path&nbsp;tmp&nbsp;=&nbsp;fs::temp_directory_path()&nbsp;/&nbsp;&quot;paths_glob_test_3&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;fs::remove_all(tmp);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;write_file(tmp&nbsp;/&nbsp;&quot;a.txt&quot;,&nbsp;&quot;A&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;write_file(tmp&nbsp;/&nbsp;&quot;b.txt&quot;,&nbsp;&quot;B&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;write_file(tmp&nbsp;/&nbsp;&quot;c.txt&quot;,&nbsp;&quot;C&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Options&nbsp;opt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;Rule&gt;&nbsp;rules&nbsp;=&nbsp;{{(tmp&nbsp;/&nbsp;&quot;*.txt&quot;).generic_string(),&nbsp;false},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{(tmp&nbsp;/&nbsp;&quot;b.txt&quot;).generic_string(),&nbsp;true}};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;out&nbsp;=&nbsp;collect_from_paths_with_excludes(rules,&nbsp;opt);<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;rel&nbsp;=&nbsp;to_rel(out,&nbsp;tmp);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;check_paths(rel,&nbsp;{&quot;a.txt&quot;,&nbsp;&quot;c.txt&quot;});<br>
}<br>
<br>
TEST_CASE(&quot;collect_from_paths_with_excludes:&nbsp;sequential&nbsp;apply&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;fs::path&nbsp;tmp&nbsp;=&nbsp;fs::temp_directory_path()&nbsp;/&nbsp;&quot;paths_glob_test_4&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;fs::remove_all(tmp);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;write_file(tmp&nbsp;/&nbsp;&quot;a.txt&quot;,&nbsp;&quot;A&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;write_file(tmp&nbsp;/&nbsp;&quot;b.txt&quot;,&nbsp;&quot;B&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;write_file(tmp&nbsp;/&nbsp;&quot;c.txt&quot;,&nbsp;&quot;C&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;write_file(tmp&nbsp;/&nbsp;&quot;d.yml&quot;,&nbsp;&quot;D&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Options&nbsp;opt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;Rule&gt;&nbsp;rules&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{(tmp&nbsp;/&nbsp;&quot;a.txt&quot;).generic_string(),&nbsp;false},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{(tmp&nbsp;/&nbsp;&quot;b.txt&quot;).generic_string(),&nbsp;false},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{(tmp&nbsp;/&nbsp;&quot;c.txt&quot;).generic_string(),&nbsp;false},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{(tmp&nbsp;/&nbsp;&quot;d.yml&quot;).generic_string(),&nbsp;false},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{(tmp&nbsp;/&nbsp;&quot;*.txt&quot;).generic_string(),&nbsp;true},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{(tmp&nbsp;/&nbsp;&quot;b.txt&quot;).generic_string(),&nbsp;false},<br>
&nbsp;&nbsp;&nbsp;&nbsp;};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;out&nbsp;=&nbsp;collect_from_paths_with_excludes(rules,&nbsp;opt);<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;rel&nbsp;=&nbsp;to_rel(out,&nbsp;tmp);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;check_paths(rel,&nbsp;{&quot;b.txt&quot;,&nbsp;&quot;d.yml&quot;});<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
