<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>tests/symbols_py.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&quot;doctest/doctest.h&quot;<br>
#include&nbsp;&quot;symbols.h&quot;<br>
<br>
#include&nbsp;&lt;string&gt;<br>
<br>
TEST_CASE(&quot;PythonSymbolFinder:&nbsp;simple&nbsp;class&nbsp;and&nbsp;methods&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;src&nbsp;=&nbsp;&quot;class&nbsp;Foo:\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;bar(self):\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;1<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;2<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;3<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;baz(self,&nbsp;x):\n&quot;&nbsp;//&nbsp;4<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;x&nbsp;+&nbsp;1\n&quot;;&nbsp;//&nbsp;5<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;PythonSymbolFinder&nbsp;finder(src);<br>
&nbsp;&nbsp;&nbsp;&nbsp;Region&nbsp;r_class;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(finder.find_class(&quot;Foo&quot;,&nbsp;r_class));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_class.start_line&nbsp;==&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_class.end_line&nbsp;==&nbsp;5);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Region&nbsp;r_bar;<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(finder.find_method(&quot;Foo&quot;,&nbsp;&quot;bar&quot;,&nbsp;r_bar));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_bar.start_line&nbsp;==&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_bar.end_line&nbsp;==&nbsp;2);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Region&nbsp;r_baz;<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(finder.find_method(&quot;Foo&quot;,&nbsp;&quot;baz&quot;,&nbsp;r_baz));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_baz.start_line&nbsp;==&nbsp;4);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_baz.end_line&nbsp;==&nbsp;5);<br>
}<br>
<br>
TEST_CASE(&quot;PythonSymbolFinder:&nbsp;ignores&nbsp;top-level&nbsp;functions&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;src&nbsp;=&nbsp;&quot;def&nbsp;foo():\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;pass\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;1<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;2<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;class&nbsp;Foo:\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;3<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;foo(self):\n&quot;&nbsp;//&nbsp;4<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass\n&quot;;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;5<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;PythonSymbolFinder&nbsp;finder(src);<br>
&nbsp;&nbsp;&nbsp;&nbsp;Region&nbsp;r_class;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(finder.find_class(&quot;Foo&quot;,&nbsp;r_class));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_class.start_line&nbsp;==&nbsp;3);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_class.end_line&nbsp;==&nbsp;5);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Region&nbsp;r_method;<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(finder.find_method(&quot;Foo&quot;,&nbsp;&quot;foo&quot;,&nbsp;r_method));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_method.start_line&nbsp;==&nbsp;4);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_method.end_line&nbsp;==&nbsp;5);<br>
}<br>
<br>
TEST_CASE(&quot;PythonSymbolFinder:&nbsp;decorated&nbsp;methods&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;src&nbsp;=&nbsp;&quot;class&nbsp;Foo:\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;@decorator\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;1<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;bar(self):\n&quot;&nbsp;//&nbsp;2<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass\n&quot;;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;3<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;PythonSymbolFinder&nbsp;finder(src);<br>
&nbsp;&nbsp;&nbsp;&nbsp;Region&nbsp;r_method;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(finder.find_method(&quot;Foo&quot;,&nbsp;&quot;bar&quot;,&nbsp;r_method));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_method.start_line&nbsp;==&nbsp;1);&nbsp;//&nbsp;вместе&nbsp;с&nbsp;декоратором<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_method.end_line&nbsp;==&nbsp;3);<br>
}<br>
<br>
TEST_CASE(&quot;PythonSymbolFinder:&nbsp;nested&nbsp;class&nbsp;and&nbsp;methods&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;src&nbsp;=&nbsp;&quot;class&nbsp;Outer:\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;a(self):\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;1<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;2<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;class&nbsp;Inner:\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;3<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;b(self):\n&quot;&nbsp;//&nbsp;4<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass\n&quot;;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;5<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;PythonSymbolFinder&nbsp;finder(src);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Region&nbsp;r_outer;<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(finder.find_class(&quot;Outer&quot;,&nbsp;r_outer));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_outer.start_line&nbsp;==&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_outer.end_line&nbsp;==&nbsp;5);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Region&nbsp;r_a;<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(finder.find_method(&quot;Outer&quot;,&nbsp;&quot;a&quot;,&nbsp;r_a));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_a.start_line&nbsp;==&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_a.end_line&nbsp;==&nbsp;2);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Region&nbsp;r_inner_class;<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(finder.find_class(&quot;Inner&quot;,&nbsp;r_inner_class));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_inner_class.start_line&nbsp;==&nbsp;3);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_inner_class.end_line&nbsp;==&nbsp;5);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Region&nbsp;r_b;<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(finder.find_method(&quot;Inner&quot;,&nbsp;&quot;b&quot;,&nbsp;r_b));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_b.start_line&nbsp;==&nbsp;4);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_b.end_line&nbsp;==&nbsp;5);<br>
}<br>
<br>
TEST_CASE(&quot;PythonSymbolFinder:&nbsp;async&nbsp;methods&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;src&nbsp;=&nbsp;&quot;class&nbsp;Foo:\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;async&nbsp;def&nbsp;bar(self):\n&quot;&nbsp;&nbsp;&nbsp;//&nbsp;1<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;await&nbsp;something()\n&quot;;&nbsp;//&nbsp;2<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;PythonSymbolFinder&nbsp;finder(src);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Region&nbsp;r_class;<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(finder.find_class(&quot;Foo&quot;,&nbsp;r_class));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_class.start_line&nbsp;==&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_class.end_line&nbsp;==&nbsp;2);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Region&nbsp;r_bar;<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(finder.find_method(&quot;Foo&quot;,&nbsp;&quot;bar&quot;,&nbsp;r_bar));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_bar.start_line&nbsp;==&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_bar.end_line&nbsp;==&nbsp;2);<br>
}<br>
<br>
TEST_CASE(&quot;PythonSymbolFinder:&nbsp;whitespace,&nbsp;comments&nbsp;and&nbsp;docstrings&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;src&nbsp;=&nbsp;&quot;#!/usr/bin/env&nbsp;python3\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;1<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;class&nbsp;&nbsp;&nbsp;Weird&nbsp;&nbsp;(&nbsp;&nbsp;Base&nbsp;&nbsp;):\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;2<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;\\\&quot;\\\&quot;\\\&quot;docstring\\\&quot;\\\&quot;\\\&quot;\n&quot;&nbsp;//&nbsp;3<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;comment&nbsp;inside&nbsp;class\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;4<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;&nbsp;&nbsp;run&nbsp;(&nbsp;self,&nbsp;&nbsp;x&nbsp;):\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;5<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;inner&nbsp;comment\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;6<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;x&nbsp;+&nbsp;1\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;7<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;8<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;def&nbsp;run(x):\n&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;9<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;x\n&quot;;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;10<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;PythonSymbolFinder&nbsp;finder(src);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Region&nbsp;r_class;<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(finder.find_class(&quot;Weird&quot;,&nbsp;r_class));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_class.start_line&nbsp;==&nbsp;2);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_class.end_line&nbsp;==&nbsp;7);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Region&nbsp;r_run;<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(finder.find_method(&quot;Weird&quot;,&nbsp;&quot;run&quot;,&nbsp;r_run));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_run.start_line&nbsp;==&nbsp;5);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(r_run.end_line&nbsp;==&nbsp;7);<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
